Reworked is_domain_valid
andresriancho/w3af pull request #17395
Opened 2018-11-09 12:51 UTC by al3xdelarge

2018-11-09 12:52 UTC, al3xdelarge commented
Sorry for the first version. That was bullshit.
Hope this one fits better.

2018-11-09 21:34 UTC, andresriancho requested changes
```
[eth:~/tools/w3af] [w3af] al3xdelarge-master+* 130 ± nosetests w3af/core/data/parsers/doc/tests/test_url.py
....................SE...........E..............................EE.............................S..................
======================================================================
ERROR: http is the default protocol, we can provide URLs with no proto
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/tests/test_url.py", line 59, in test_default_proto
    u = URL('w3af.com')
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/url.py", line 246, in __init__
    netloc = path
UnboundLocalError: local variable 'path' referenced before assignment

======================================================================
ERROR: test_from_url (w3af.core.data.parsers.doc.tests.test_url.TestURLParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/tests/test_url.py", line 687, in test_from_url
    o = URL('w3af.com')
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/url.py", line 246, in __init__
    netloc = path
UnboundLocalError: local variable 'path' referenced before assignment

======================================================================
ERROR: test_is_valid_domain_invalid (w3af.core.data.parsers.doc.tests.test_url.TestURLParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/tests/test_url.py", line 604, in test_is_valid_domain_invalid
    self.assertFalse(URL('http://aaa*a').is_valid_domain())
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/url.py", line 582, in is_valid_domain
    socket.inet_aton(parsed_url.hostname)
NameError: global name 'parsed_url' is not defined

======================================================================
ERROR: test_is_valid_domain_valid (w3af.core.data.parsers.doc.tests.test_url.TestURLParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/tests/test_url.py", line 592, in test_is_valid_domain_valid
    self.assertTrue(URL('http://1.2.3.4').is_valid_domain())
  File "/home/eth/tools/w3af/w3af/core/data/parsers/doc/url.py", line 582, in is_valid_domain
    socket.inet_aton(parsed_url.hostname)
NameError: global name 'parsed_url' is not defined

----------------------------------------------------------------------
Ran 114 tests in 0.093s

FAILED (SKIP=2, errors=4)
```

2018-11-09 21:34 UTC, andresriancho commented on w3af/core/data/parsers/doc/url.py
>              netloc = path
`path` is not defined here.

2018-11-09 21:34 UTC, andresriancho commented on w3af/core/data/parsers/doc/url.py
> +        self._hostname = None
You added this attribute here and to `__slots__` and then never used it? It is confusing to see `self._hostname` and `self.hostname`

2018-11-09 21:34 UTC, andresriancho commented on w3af/core/data/parsers/doc/url.py
> +                socket.inet_aton(parsed_url.hostname)
`parsed_url` is not defined.

2019-02-05 11:40 UTC, andresriancho commented
All tests fail!

```
[eth:~/tools/w3af-experiments] [w3af] al3xdelarge-master* 130 ± nosetests w3af/core/data/parsers/doc/tests/test_url.py
EEEEEEEEEEEEEEEEEEEESEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.EEEEEEEEE........EEEEEEEEEEEEEEEESEEEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_add (w3af.core.data.parsers.doc.tests.test_url.TestURLParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af-experiments/w3af/core/data/parsers/doc/tests/test_url.py", line 997, in test_add
    u = URL('http://www.w3af.com/')
  File "/home/eth/tools/w3af-experiments/w3af/core/data/parsers/doc/url.py", line 256, in __init__
    self.hostname = parsed.hostname or u''
AttributeError: 'URL' object has no attribute 'hostname'

======================================================================
ERROR: test_all_but_scheme (w3af.core.data.parsers.doc.tests.test_url.TestURLParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eth/tools/w3af-experiments/w3af/core/data/parsers/doc/tests/test_url.py", line 547, in test_all_but_scheme
    self.assertEqual(URL('https://w3af.com:443/xyz/').all_but_scheme(),
  File "/home/eth/tools/w3af-experiments/w3af/core/data/parsers/doc/url.py", line 256, in __init__
    self.hostname = parsed.hostname or u''
AttributeError: 'URL' object has no attribute 'hostname'
```

Are you running a test scan after making your changes?

2019-02-07 10:36 UTC, al3xdelarge commented
Sorry. Now they should pass.

2019-03-02 17:39 UTC, andresriancho commented
Merged!

![giphy](https://user-images.githubusercontent.com/865200/53685404-ebf88700-3cf8-11e9-9e4f-a6cd5188a005.gif)

2019-03-02 17:39 UTC, closed without merging